version: '3.8'

services:
  # Development services with live reload
  python-dev:
    build:
      context: ./python
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./python:/app
    networks:
      - dev-network

  nodejs-dev:
    build:
      context: ./nodejs
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./nodejs:/app
      - /app/node_modules
    networks:
      - dev-network

  java-dev:
    build:
      context: ./java
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./java:/app
    networks:
      - dev-network

  go-dev:
    build:
      context: ./golang
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8090"
    environment:
      - GO_ENV=development
    volumes:
      - ./golang:/app
    networks:
      - dev-network

  dotnet-dev:
    build:
      context: ./dotnet
      dockerfile: Dockerfile.dev
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./dotnet:/app
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge